name: Deploy Branch

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: |
        export MKCERT_VERSION=v1.4.4
        export PLATFORM=linux
        curl -L "https://github.com/FiloSottile/mkcert/releases/download/$MKCERT_VERSION/mkcert-$MKCERT_VERSION-$PLATFORM-amd64" -o mkcert
        chmod +x mkcert
        echo "$PWD/mkcert" >> $GITHUB_PATH
        mkdir -p src/certs
        ./mkcert -cert-file src/certs/cert.pem -key-file src/certs/cert.key localhost 127.0.0.1
    - run: npm ci
      working-directory: ./src
    - run: npm run build --if-present
      working-directory: ./src
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./src
    - name: Run Playwright tests
      run: npm test
      working-directory: ./src
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./src/playwright-report
        retention-days: 30
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_DEPLOY_REGION }}
        role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
    - name: AWS Deploy
      run: |
        aws sts get-caller-identity
        aws s3 sync ./dist s3://${{ vars.AWS_DEPLOY_S3_BUCKET_NAME }} --delete
        aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_DEPLOY_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
